phi-jp/meltline

src/responsive.less
- flexbox系のl-flex-*がなかったので追加しました。
- フォントサイズのl-fs*がなかったので追加しました。
- ラインハイトのl-lh*がなかったので追加しました。
=> responsiveでdesktop用の値が無いものを追加

src/flexbox.less
=> flex box の baseline の追加

src/font.less
=> text-justifyを追加しました

src/responsive.less
=> l-text-left追加

src/flexbox.less
- center,flex-start,flex-end,stretch,baselineを追加
=> align-self系を追加

src/responsive.less
=> white-space系のレスポンシブクラスを追加

src/responsive.less
- s-letter-spacing,m-letter-spacing,l-letter-spacingを追加
=> letter-spacingのレスポンシブ対応

src/font.less
- 1以下の`letter-spacing`を作成
- レスポンシブも対応
=> letter-spacin-0_○系を追加

src/responsive.less
- flex,flex-top,flex-bottom,flex-right,flex-left,flex-center,flex-around,flex-between,flex-heart,flex-auto,flex-fixedのs,m,l対応をしました
=> s,m,lサイズ用のflexやflex-middleなどの対応

src/box.less
- box.lessのborderにoutline-noneを追加
=> outline-noneを追加

src/box.less
- roundedの1~32, 100を追加
- numsが使えないのでハードコーティグ
=> 1~32, 100のroundedを追加

src/flexbox.less
=> orderからpxを削除

src/util.less
```
.scrollbar-none, .scrollbar-hide {
&::-webkit-scrollbar {
display: none;
}
}
```
上記を追加しました！
=> scrollbar-none追加

src/util.less
.writing-horizontal-tb {  writing-mode: horizontal-tb; }
.writing-vertical-lr {  writing-mode: vertical-lr; }
.writing-vertical-rl {  writing-mode: vertical-rl; }
上記３つ追加
=> writing-mode追加

src/util.less
```
.box-shadow {
box-shadow: 0px 0px 4px 0px #222;
}
.box-shadow-1 {
box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
}
.box-shadow-2 {
box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
}
.box-shadow-3 {
box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
}
.box-shadow-4 {
box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
}
.box-shadow-5 {
box-shadow: 0 19px 38px rgba(0, 0, 0, 0.30), 0 15px 12px rgba(0, 0, 0, 0.22);
}
```
=> box-shadow追加

src/color.less
borderにグラデーションが効かない
```
.border-@{key} {
border-color: @a;
}
```
↓
```
.border-@{key} {
border-image: linear-gradient(@angle, @a 0%, @b 100%);
border-image-slice: 1;
}
```
https://junjun-web.net/css/css-border-bottom-gradation/
=> border-colorをグラデーションにする

src/color.less
=> text-やbg-なし指定を廃止

meltline.css, src/util.less
=> transitionを追加

src/util.less
=> hover-underline追加

index.html, src/anim.less, src/index.less
npm run dev して /index.html#animation で確認できます!
=> アニメーションを追加

src/box.less, src/index.less, src/method.less, src/responsive.less, src/size.less
meltline の method をクライアント側で import して使えるよう修正
```
@import "~meltline/src/method.less";
.define-color(primary, #abffff);
.define-size(77 122);
.define-padding(77 122);
.define-margin(77 122);
.define-rounded(300);
.define-rect(rect_origin, 8, 10);
```
=> method を外から使えるよう修正

src/flexbox.less
`justify-content: space-evenly;`を追加
=> flex-evenly追加

src/method.less
`max-width-○`
`min-width-○`
`max-height-○`
`min-height-○`
=> methodにmax, minのsize追加

src/method.less
- positionのメソッドを追加
- 一旦negativeはいれてない(追加する？)
=> positionのメソッド追加

src/font.less, src/responsive.less
- line-clampのs,m,l追加
- rowのs,m,l追加
=> line-clampとrowのs,m,l追加

src/method.less
- define-colorのcss変数定義
[alog] (https://alog.team/workspaces/uRFSioAqv62eVHwR8_li0crEDWtc8irtkQh1ry55YiE/projects/aRudeseAor1q1WmavCGU/notes/c8g82ua23akg02kqhcc0?view=board)
検証動画
https://www.awesomescreenshot.com/video/7774895?key=566e889447ad05a896d00b976c673c36
=> define-colorのcss変数定義

src/method.less
- px, em, rem, %の4種
- `define-font-size`で定義
=> methodにfont-sizeを追加できるようにする
